import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/nav/NavBar";
import { Toast } from "@heroui/react";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col bg-gray-100">
        <Providers>
          <Toast.Provider />
          <NavBar />
          <main className="container mx-auto mt-18">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
