import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/nav/NavBar";
import { Toast } from "@heroui/react";

export const metadata: Metadata = {
  title: "next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col bg-gray-100">
        <Toast.Provider />
        <NavBar />
        <main className="container mx-auto mt-24">{children}</main>
      </body>
    </html>
  );
}
